### PR TITLE
check tif file extension requirement

### LINKED ISSUE #12: Biodiversity Intactness Index originally comes as ASCII file
Hi @karpfen,

when downloading the zip file from the linked source [here](https://data.nhm.ac.uk/dataset/global-map-of-the-biodiversity-intactness-index-from-newbold-et-al-2016-science) the data is an ASCII file, however, the source code does not translate to e.g. GeoTiff. To achieve this it would simply require to specify the `filenames` argument with the `.tif` file extension. Could you please adjust?

https://github.com/mapme-initiative/mapme.indicators/blob/9ed10365b19db91734eb6d0d783a7d909d42f39d/R/get_biodiversity_intactness_index.R#L33-L36

### PR DESCRIPTION
**Pull request by karpfen**
This commit should fix #12 .
@goergen95 do you mind taking a look? Thanks!

### CODE REVIEW

**Comment by goergen95** [comment]
Hi @karpfen,
I think asking users to translate to GTiff manually introduces an unwanted source of error. I adapted the code to consume the original `.asc` file instead. Could you test if everything works as expected (note: needs recent `mapme.biodiversity` branch `dev`).

**Comment by karpfen** [comment]
Looks good to me, @goergen95. One question though: you named the sample file `lbii.asc`, instead of `bii.asc`. Does the "l" at the beginning have a meaning or was that a typo?

**Comment by goergen95** [comment]
I think that is the name of the file from the zip archive, is it not?

**Comment by karpfen** [comment]
Ah, true. Then we're good to go

**Pull request merged**
