### PR TITLE
Fixes carbon calculation per area

### PR DESCRIPTION
**Pull request by goergen95**

### CODE REVIEW

**Comment by karpfen** [comment]
@goergen95 I wanted to try a couple of sanity checks before merging this, but I'm having trouble downloading the carbon data right now.
Do you need this merged immediately or can I try later and then get back to you?

**Comment by goergen95** [comment]
Its alright! Better save than sorry ;)

**Comment by karpfen** [comment]
@goergen95 I'm still having trouble downloading the resource, but I think it's not the timeout anymore:

```r
> options(timeout = 15000)
> aoi <- system.file("extdata", "sierra_de_neiba_478140_2.gpkg",
+                    package = "mapme.biodiversity"
+ ) |>
+   read_sf() |>
+   get_resources(get_irr_carbon())
trying URL 'https://zenodo.org/api/records/4091029/files/Irrecoverable_Carbon_2010.zip/content'
Content type 'application/octet-stream' length 2033474374 bytes (1939.3 MB)
downloaded 1939.3 MB

trying URL 'https://zenodo.org/api/records/4091029/files/Irrecoverable_Carbon_2018.zip/content'
Content type 'application/octet-stream' length 2018917016 bytes (1925.4 MB)
downloaded 1925.4 MB

Error in st_sf(x, ..., agr = agr, sf_column_name = sf_column_name) : 
  no simple features geometry column present
In addition: Warning messages:
1: In unzip(filename, junkpaths = TRUE, exdir = tmpdir) :
  internal error in 'unz' code
2: In unzip(filename, junkpaths = TRUE, exdir = tmpdir) :
  internal error in 'unz' code
Error in .check_footprints(resource, resource_name) : 
  Download for resource irr_carbon failed.
Returning unmodified portfolio.
```

I don't understand waht's going on there, do you have an idea?

**Comment by goergen95** [comment]
Nope, can't reproduce. Works for me... Can you re-install `mapme.biodiversity`? Maybe you have an older version installed which does not go well with this branch?

**Comment by karpfen** [comment]
Is the CRAN version sufficient?

**Comment by goergen95** [comment]
Yep, should be compatible with v0.8.0

**Comment by karpfen** [comment]
@goergen95: I managed to get the resources working now. The problem was with the raw data download. The zip archives were downloaded seemingly completely, also with a realistic file size. But the md5sum was off and the zip archives invalid. I downloaded them manually, then it worked.

I now ran some tests to see if the indicator results add up with what I'd expect, but they were way off. Maybe we can take a look at this together if you have time:

```r
devtools::load_all()
library(mapme.biodiversity)
library(sf)
library(terra)
library(dplyr)


mapme_options(
  outdir = "C:/data/mapme.biodiversity/",
  verbose = FALSE
)
options(timeout = 15000)

aoi <- system.file("extdata", "sierra_de_neiba_478140_2.gpkg",
                   package = "mapme.biodiversity") |>
  read_sf()
vc <- aoi |>
  get_resources(
    get_vul_carbon()
  ) |>
  calc_indicators(
    calc_vul_carbon(stats = c("sum", "var", "mean"))
  ) |>
  portfolio_long(drop_geoms = TRUE) |>
  filter(datetime == "2010-01-01")

vul_c_total_2010 <- rast("C:/data/mapme.biodiversity/vul_carbon/Vulnerable_C_Total_2010.tif") |>
  crop(aoi) |>
  mask(aoi)


vc |>
  filter(variable == "vul_carbon_total_sum") |>
  select(value) |>
  pull()
# 2483239
sum(values(vul_c_total_2010), na.rm = TRUE)
# 331681


vul_c_total_2010 |>
  values() |>
  as.numeric() |>
  mean(na.rm = TRUE)
# 148.8026
vc |>
  filter(variable == "vul_carbon_total_mean") |>
  select(value) |>
  pull()
# 1375.143



vc |>
  filter(variable == "vul_carbon_total_var") |>
  select(value) |>
  pull()
# 35748255234
vul_c_total_2010 |>
  values() |>
  as.numeric() |>
  var(na.rm = TRUE)
# 6394.929

vc |>
  filter(variable == "vul_carbon_total_var") |>
  select(unit) |>
  pull()
# "Mg"
# expected: Mg^2
```

**Comment by goergen95** [comment]
Hi  @karpfen, I am currently investigating your example and I am missing the central issue of this PR. 
In the original data, a pixels value means `Mg/ha`. If we want to calculate a zonal statistic for this, we need to convert this to `Mg/pixel`. So, when adding the following to your code

```r
vul_c_total_2010 <- vul_c_total_2010 * cellSize(vul_c_total_2010, unit = "ha")
```

I get more sensible values (though the variance value seems far off to be honest). Those differences could be explained by the choice of the `engine`, I'd guess. What do you think?

**Comment by goergen95** [comment]
I see:

```r
carbon <- rast("Vulnerable_C_Total_2010.tif")
carbon <- crop(carbon, aoi)
carbon <- carbon * cellSize(carbon, unit = "ha")

tibble::tibble(
terra_zonal = zonal(carbon, vect(aoi), sum, na.rm = T)[[1]],
terra_extract = extract(carbon, vect(aoi), sum, na.rm = T)[, 2],
exact = exactextractr::exact_extract(carbon, aoi, "sum"),
mapme_zonal = mapme.biodiversity::select_engine(aoi, carbon, "sum", "zonal")[[1]],
mapme_extract = mapme.biodiversity::select_engine(aoi, carbon, "sum", "extract")[[1]],
mapme_exact = mapme.biodiversity::select_engine(aoi, carbon, "sum", "exactextract")[[1]]
)
> # A tibble: 1 × 6
>  terra_zonal terra_extract    exact mapme_zonal mapme_extract mapme_exact
>        <dbl>         <dbl>    <dbl>       <dbl>         <dbl>       <dbl>>
> 1    2478013.      2478013. 2474650.    2478013.      2478013.    2474650.

**Comment by karpfen** [comment]
Aah, now it makes sense. I'd assumed that the raw data was the absolute carbon mass per pixel. Cool, in that case the PR looks fine to me.
Except maybe the unit for `var`, which should be Mg^2 IMO. What do you think about that?

**Comment by goergen95** [comment]
Currently trying to figure out if I can get an exact matching of the values but it does not work right now. Will further investigate where the differences might come from (though they are not as sever as per your first example):

```r
remotes::install_github("mapme-initiative/mapme.indicators", ref = "fix-carbon-per-pixel")
library(mapme.indicators)
library(sf)
library(terra)
library(dplyr)


mapme_options(
  outdir = "/home/rstudio/mapme/data/",
  chunk_size = 1e8,
  verbose = FALSE
)
options(timeout = 15000)

aoi <- system.file("extdata", "sierra_de_neiba_478140_2.gpkg",
                   package = "mapme.biodiversity") |>
  read_sf()

get_resources(aoi, get_vul_carbon())
carbon <- prep_resources(aoi)$vul_carbon[[1]]
carbon <- crop(carbon, aoi, snap = "out")
carbon <- carbon * cellSize(carbon, unit = "ha")

print(carbon)

tibble::tibble(
terra_zonal = zonal(carbon, vect(aoi), sum, na.rm = T)[[1]],
terra_extract = extract(carbon, vect(aoi), sum, na.rm = T)[, 2],
exact = exactextractr::exact_extract(carbon, aoi, "sum"),
engine_zonal = mapme.biodiversity::select_engine(aoi, carbon, "sum", "zonal")[[1]],
engine_extract = mapme.biodiversity::select_engine(aoi, carbon, "sum", "extract")[[1]],
engine_exact = mapme.biodiversity::select_engine(aoi, carbon, "sum", "exactextract")[[1]],
mapme_zonal = calc_indicators(aoi, calc_vul_carbon(type = "biomass", stats = "sum", engine = "zonal"))$vul_carbon[[1]][["value"]][1],
mapme_extract = calc_indicators(aoi, calc_vul_carbon(type = "biomass", stats = "sum", engine = "extract"))$vul_carbon[[1]][["value"]][1],
mapme_exact = calc_indicators(aoi, calc_vul_carbon(type = "biomass", stats = "sum", engine = "exactextract"))$vul_carbon[[1]][["value"]][1]
)

# A tibble: 1 × 9
  terra_zonal terra_extract   exact engine_zonal engine_extract engine_exact mapme_zonal mapme_extract mapme_exact
        <dbl>         <dbl>   <dbl>        <dbl>          <dbl>        <dbl>       <dbl>         <dbl>       <dbl>
1     943078.       943078. 943600.      943078.        943078.      943600.     943078.       943078.     943600.
```

**Comment by goergen95** [comment]
Got it! There will be differences due to chunking applied when `chunk_size` is smaller then the aoi's bounding box. I adapted above example with a chunks size well above that threshold and we obtain identical results now. 

Concerning the variance: I am not sure about the units, will have to think about it. About the difference in values: I also suspect chunking to play a role here. We aggregate the statistics of chunks by applying the statistic itself, e.g. the sum of sums, or, in this case, the variance of variances.

**Pull request merged**
