### PR TITLE
Calculate GSW timeseries indicator

### PR DESCRIPTION
**Pull request by karpfen**

### CODE REVIEW

**Comment by karpfen** [comment]
@goergen95 After switching the register_resource() with .register() call, both devtools::test() and devtools::check() work as expected for me. Can you please check if this also works on your side?

**Comment by goergen95** [comment]
Yep, works for me too, except that I get the following output:

```r
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test-calc_gsw_time_series.R:33:3'): calc_gsw_time_series works ────
aoi[[indicator_colname]][[1]][["gsw_permanent_water_ha"]] (`actual`) not equal to c(1346, 1358) (`expected`).

  `actual`: 1338 1350
`expected`: 1346 1358

[ FAIL 1 | WARN 0 | SKIP 0 | PASS 34 ]
Error: Test failures
Execution halted
```

**Comment by goergen95** [comment]
I have `Linking to GEOS 3.12.1, GDAL 3.8.2, PROJ 9.3.1; sf_use_s2() is TRUE` and the sessionInfo() output below:
<details>
R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Berlin
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] sf_1.0-16                     mapme.indicators_0.0.1.9000  
[3] mapme.biodiversity_0.5.0.9001

loaded via a namespace (and not attached):
 [1] xfun_0.42            raster_3.6-26        httr2_1.0.0         
 [4] htmlwidgets_1.6.4    devtools_2.4.5       remotes_2.4.2.1     
 [7] processx_3.8.3       lattice_0.22-5       callr_3.7.5         
[10] ps_1.7.6             vctrs_0.6.5          tools_4.3.2         
[13] generics_0.1.3       curl_5.2.1           tibble_3.2.1        
[16] proxy_0.4-27         fansi_1.0.6          pkgconfig_2.0.3     
[19] KernSmooth_2.23-22   xopen_1.0.0          desc_1.4.3          
[22] lifecycle_1.0.4      compiler_4.3.2       stringr_1.5.1       
[25] terra_1.7-74         codetools_0.2-19     httpuv_1.6.14       
[28] htmltools_0.5.7      usethis_2.2.3        class_7.3-22        
[31] later_1.3.2          pillar_1.9.0         exactextractr_0.10.0
[34] urlchecker_1.0.1     tidyr_1.3.1          ellipsis_0.3.2      
[37] classInt_0.4-10      cachem_1.0.8         sessioninfo_1.2.2   
[40] mime_0.12            commonmark_1.9.1     tidyselect_1.2.1    
[43] digest_0.6.35        stringi_1.8.3        dplyr_1.1.4         
[46] purrr_1.0.2          rprojroot_2.0.4      fastmap_1.1.1       
[49] grid_4.3.2           cli_3.6.2            magrittr_2.0.3      
[52] pkgbuild_1.4.3       utf8_1.2.4           e1071_1.7-14        
[55] withr_3.0.0          prettyunits_1.2.0    promises_1.2.1      
[58] rappdirs_0.3.3       sp_2.1-3             roxygen2_7.3.1      
[61] memoise_2.0.1        shiny_1.8.0          knitr_1.45          
[64] rcmdcheck_1.4.0      miniUI_0.1.1.1       profvis_0.3.8       
[67] rlang_1.1.3          Rcpp_1.0.12          xtable_1.8-4        
[70] glue_1.7.0           DBI_1.2.2            xml2_1.3.6          
[73] pkgload_1.3.4        rstudioapi_0.15.0    R6_2.5.1            
[76] fs_1.6.3             units_0.8-5         
</details>

**Comment by goergen95** [comment]
@karpfen added CI and update this branch. Let's wait for the check results.

**Comment by karpfen** [comment]
Hmmmm....I don't understand. My library versions should be ok, right?
Do you know if `terra` behaves differently in Windows/Unix systems, @goergen95? 

`Linking to GEOS 3.11.2, GDAL 3.7.2, PROJ 9.3.0; sf_use_s2() is TRUE`

<details><summary>session info</summary>
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mapme.indicators_0.0.1.9000 purrr_1.0.2                 mapme.biodiversity_0.5.0    testthat_3.2.1              sf_1.0-15                  

loaded via a namespace (and not attached):
 [1] raster_3.6-26        httr2_1.0.0          htmlwidgets_1.6.4    devtools_2.4.5       remotes_2.5.0        lattice_0.22-6       vctrs_0.6.5         
 [8] tools_4.3.2          generics_0.1.3       parallel_4.3.2       curl_5.2.1           tibble_3.2.1         proxy_0.4-27         fansi_1.0.6         
[15] pkgconfig_2.0.3      KernSmooth_2.23-22   desc_1.4.3           lifecycle_1.0.4      compiler_4.3.2       stringr_1.5.1        brio_1.1.4          
[22] terra_1.7-71         codetools_0.2-19     httpuv_1.6.14        htmltools_0.5.7      usethis_2.2.3        class_7.3-22         furrr_0.3.1         
[29] later_1.3.2          pillar_1.9.0         exactextractr_0.10.0 urlchecker_1.0.1     tidyr_1.3.1          ellipsis_0.3.2       classInt_0.4-10     
[36] cachem_1.0.8         wk_0.9.1             sessioninfo_1.2.2    parallelly_1.37.1    mime_0.12            tidyselect_1.2.1     digest_0.6.35       
[43] future_1.33.1        stringi_1.8.3        listenv_0.9.1        dplyr_1.1.4          rprojroot_2.0.4      fastmap_1.1.1        grid_4.3.2          
[50] cli_3.6.2            magrittr_2.0.3       pkgbuild_1.4.4       utf8_1.2.4           e1071_1.7-14         withr_3.0.0          waldo_0.5.2         
[57] promises_1.2.1       rappdirs_0.3.3       sp_2.1-3             timechange_0.3.0     lubridate_1.9.3      globals_0.16.3       progressr_0.14.0    
[64] memoise_2.0.1        shiny_1.8.0          miniUI_0.1.1.1       s2_1.1.6             profvis_0.3.8        rlang_1.1.3          Rcpp_1.0.12         
[71] xtable_1.8-4         glue_1.7.0           DBI_1.2.2            pkgload_1.3.4        jsonlite_1.8.8       rstudioapi_0.15.0    R6_2.5.1            
[78] fs_1.6.3             units_0.8-5 
</details>

**Comment by goergen95** [comment]
nope, not sure what is causing this... I see that I did not include tests for the numerical results for the other indicators. Maybe that's the better approach?

**Comment by karpfen** [comment]
Yeah, sounds good to me. Would be interesting to know what caused this, though. Not right now, though :)

**Comment by goergen95** [comment]
Would be better to figure it out now... It's strange, I guess we should see the same over at mapme.biodiversity. Maybe different package builds are used in the CI runs..

**Comment by goergen95** [comment]
And there was only a difference in the last of the three classes, right? That is very strange, too...

**Pull request closed without merging**
